strange, workaround for
  File "/nfsmnt/sra0/sra/souren/trust-metrics/trustlet/pymmetry/tm_calc.py", line 244, in tmetric_calc
    self.tmetric_run(idxn, seeds, caps, tmetric_type)
  File "/nfsmnt/sra0/sra/souren/trust-metrics/trustlet/pymmetry/tm_calc.py", line 200, in tmetric_run
    flow = self.flows[i].netflow_max_flow_extract(dn_seed, caps)
  File "/nfsmnt/sra0/sra/souren/trust-metrics/trustlet/pymmetry/net_flow.py", line 749, in netflow_max_flow_extract
    priv = self.netflow_max_flow(seed, caps)
  File "/nfsmnt/sra0/sra/souren/trust-metrics/trustlet/pymmetry/net_flow.py", line 736, in netflow_max_flow
    priv.netflow_max_flow(seed, pred_list, node_list)
  File "/nfsmnt/sra0/sra/souren/trust-metrics/trustlet/pymmetry/net_flow.py", line 484, in netflow_max_flow
    while self.netflow_augment(seed, node_list):
  File "/nfsmnt/sra0/sra/souren/trust-metrics/trustlet/pymmetry/net_flow.py", line 367, in netflow_augment
    self.debug("add %do to queue" % src)
TypeError: int argument required